apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-produktside-prototype
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /prototype/produktside/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /prototype/produktside/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  ingresses:
    - "https://www.ansatt.dev.nav.no/prototype/produktside"
  resources:
    requests:
      cpu: "20m"
      memory: 128Mi
    limits:
      memory: 512Mi
